import type {
  Client,
  Technician,
  ServiceOrder,
  InventoryItem,
  Quote,
  Invoice,
  ActivityEvent,
} from "./types";

// Fecha relativa a hoy → mantiene la banda de urgencias siempre viva.
function rel(days: number): string {
  const d = new Date();
  d.setHours(9, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const technicians: Technician[] = [
  {
    id: "t1",
    name: "Ramón Peralta",
    phone: "809-555-0142",
    specialties: ["Instalaciones residenciales", "Paneles solares"],
    certifications: ["Electricista certificado CNE", "Instalador solar Nivel II"],
    activeOrders: 4,
  },
  {
    id: "t2",
    name: "Wander Batista",
    phone: "829-555-0177",
    specialties: ["Sistemas comerciales", "Breakers y tableros"],
    certifications: ["Electricista certificado CNE"],
    activeOrders: 3,
  },
  {
    id: "t3",
    name: "Franklin Ureña",
    phone: "849-555-0198",
    specialties: ["Cámaras y alarmas", "Cableado estructurado"],
    certifications: ["Técnico en CCTV", "Redes de baja tensión"],
    activeOrders: 2,
  },
  {
    id: "t4",
    name: "Yohan Mercedes",
    phone: "809-555-0231",
    specialties: ["Aire acondicionado", "Mantenimiento preventivo"],
    certifications: ["Técnico HVAC", "Electricista certificado CNE"],
    activeOrders: 3,
  },
];

export const clients: Client[] = [
  {
    id: "c1",
    name: "Residencial Los Cacicazgos",
    phone: "809-482-1120",
    address: "Av. Anacaona 45, Los Cacicazgos, Santo Domingo",
    propertyType: "residencial",
    panelType: "Panel Square D 200A",
    voltage: "120/240V monofásico",
    notes: "Panel principal en garaje. Cliente prefiere visitas AM.",
    totalSpent: 486_500,
    serviceCount: 7,
    createdAt: rel(-320),
  },
  {
    id: "c2",
    name: "Supermercado La Cadena — Suc. Naco",
    phone: "809-565-4400",
    address: "Calle Fantino Falco 12, Naco, Santo Domingo",
    propertyType: "comercial",
    panelType: "Tablero trifásico 400A",
    voltage: "208/120V trifásico",
    notes: "Cuartos fríos con circuito dedicado. Coordinar fuera de horario pico.",
    totalSpent: 1_284_000,
    serviceCount: 14,
    createdAt: rel(-410),
  },
  {
    id: "c3",
    name: "Ferretería El Tornillo Feliz",
    phone: "829-771-3388",
    address: "Av. Duarte 210, Villa Consuelo, Santo Domingo",
    propertyType: "comercial",
    panelType: "Panel 100A",
    voltage: "120/240V monofásico",
    notes: "Solicitó cotización de planta eléctrica de respaldo.",
    totalSpent: 218_900,
    serviceCount: 4,
    createdAt: rel(-180),
  },
  {
    id: "c4",
    name: "Industrias Metálicas del Caribe",
    phone: "809-333-9021",
    address: "Zona Franca Industrial, Km 22 Autopista Duarte",
    propertyType: "industrial",
    panelType: "Subestación 500 KVA",
    voltage: "480V trifásico",
    notes: "Contrato de mantenimiento trimestral. Acceso con carné.",
    totalSpent: 2_940_000,
    serviceCount: 21,
    createdAt: rel(-520),
  },
  {
    id: "c5",
    name: "Dra. Mariela Fernández",
    phone: "809-604-7712",
    address: "Torre Piantini, Apto 8B, Piantini, Santo Domingo",
    propertyType: "residencial",
    panelType: "Panel 150A",
    voltage: "120/240V monofásico",
    notes: "Instalación de cargador para vehículo eléctrico pendiente.",
    totalSpent: 96_400,
    serviceCount: 2,
    createdAt: rel(-95),
  },
  {
    id: "c6",
    name: "Colmadón El Buen Precio",
    phone: "849-210-5567",
    address: "Calle Respaldo 8, Los Mina, Santo Domingo Este",
    propertyType: "comercial",
    panelType: "Panel 100A",
    voltage: "120/240V monofásico",
    notes: "Nevera y congeladores en un solo circuito — recomendar separar.",
    totalSpent: 54_200,
    serviceCount: 3,
    createdAt: rel(-60),
  },
  {
    id: "c7",
    name: "Hotel Boutique Villa Serena",
    phone: "809-712-8890",
    address: "Calle El Conde 102, Zona Colonial, Santo Domingo",
    propertyType: "comercial",
    panelType: "Tablero trifásico 300A",
    voltage: "208/120V trifásico",
    notes: "Sistema de cámaras de 16 canales instalado por JM.",
    totalSpent: 672_300,
    serviceCount: 9,
    createdAt: rel(-240),
  },
  {
    id: "c8",
    name: "Sr. Ampáro Guzmán",
    phone: "829-448-1234",
    address: "Res. Villa Olga, Calle 3 #17, Santiago",
    propertyType: "residencial",
    panelType: "Panel 125A",
    voltage: "120/240V monofásico",
    notes: "Instalación de paneles solares de 5kW completada.",
    totalSpent: 412_800,
    serviceCount: 5,
    createdAt: rel(-150),
  },
];

export const serviceOrders: ServiceOrder[] = [
  {
    id: "o1",
    number: "OS-2025-0148",
    clientId: "c2",
    clientName: "Supermercado La Cadena — Suc. Naco",
    serviceType: "reparacion",
    status: "en_proceso",
    priority: "urgente",
    technicianIds: ["t2"],
    technicianNames: ["Wander Batista"],
    scheduledDate: rel(-1),
    estimatedEndDate: rel(0),
    description: "Falla en circuito de cuartos fríos. Breaker principal disparando.",
    address: "Calle Fantino Falco 12, Naco",
    total: 38_500,
    createdAt: rel(-2),
  },
  {
    id: "o2",
    number: "OS-2025-0149",
    clientId: "c4",
    clientName: "Industrias Metálicas del Caribe",
    serviceType: "mantenimiento",
    status: "asignada",
    priority: "normal",
    technicianIds: ["t1", "t2"],
    technicianNames: ["Ramón Peralta", "Wander Batista"],
    scheduledDate: rel(-3),
    estimatedEndDate: rel(-1),
    description: "Mantenimiento trimestral de subestación 500 KVA.",
    address: "Zona Franca Industrial, Km 22",
    total: 145_000,
    createdAt: rel(-6),
  },
  {
    id: "o3",
    number: "OS-2025-0150",
    clientId: "c5",
    clientName: "Dra. Mariela Fernández",
    serviceType: "instalacion_nueva",
    status: "esperando_materiales",
    priority: "normal",
    technicianIds: ["t1"],
    technicianNames: ["Ramón Peralta"],
    scheduledDate: rel(0),
    estimatedEndDate: rel(1),
    description: "Instalación de cargador para vehículo eléctrico (NEMA 14-50).",
    address: "Torre Piantini, Apto 8B, Piantini",
    total: 62_400,
    createdAt: rel(-4),
  },
  {
    id: "o4",
    number: "OS-2025-0151",
    clientId: "c7",
    clientName: "Hotel Boutique Villa Serena",
    serviceType: "camaras",
    status: "en_proceso",
    priority: "normal",
    technicianIds: ["t3"],
    technicianNames: ["Franklin Ureña"],
    scheduledDate: rel(0),
    estimatedEndDate: rel(2),
    description: "Ampliación a 16 canales de CCTV y grabador NVR.",
    address: "Calle El Conde 102, Zona Colonial",
    total: 118_900,
    createdAt: rel(-5),
  },
  {
    id: "o5",
    number: "OS-2025-0152",
    clientId: "c6",
    clientName: "Colmadón El Buen Precio",
    serviceType: "emergencia",
    status: "recibida",
    priority: "emergencia",
    technicianIds: [],
    technicianNames: [],
    scheduledDate: rel(0),
    estimatedEndDate: rel(0),
    description: "Sin energía en toda la nevera. Pérdida de mercancía en riesgo.",
    address: "Calle Respaldo 8, Los Mina",
    total: 0,
    createdAt: rel(0),
  },
  {
    id: "o6",
    number: "OS-2025-0153",
    clientId: "c1",
    clientName: "Residencial Los Cacicazgos",
    serviceType: "aire_acondicionado",
    status: "asignada",
    priority: "normal",
    technicianIds: ["t4"],
    technicianNames: ["Yohan Mercedes"],
    scheduledDate: rel(1),
    estimatedEndDate: rel(1),
    description: "Instalación de 2 unidades split de 24,000 BTU.",
    address: "Av. Anacaona 45, Los Cacicazgos",
    total: 84_000,
    createdAt: rel(-1),
  },
  {
    id: "o7",
    number: "OS-2025-0154",
    clientId: "c8",
    clientName: "Sr. Amparo Guzmán",
    serviceType: "paneles_solares",
    status: "completada",
    priority: "normal",
    technicianIds: ["t1"],
    technicianNames: ["Ramón Peralta"],
    scheduledDate: rel(-8),
    estimatedEndDate: rel(-5),
    description: "Sistema solar de 5kW con 12 paneles e inversor híbrido.",
    address: "Res. Villa Olga, Santiago",
    total: 412_800,
    createdAt: rel(-14),
  },
  {
    id: "o8",
    number: "OS-2025-0155",
    clientId: "c3",
    clientName: "Ferretería El Tornillo Feliz",
    serviceType: "diagnostico",
    status: "en_proceso",
    priority: "normal",
    technicianIds: ["t2"],
    technicianNames: ["Wander Batista"],
    scheduledDate: rel(2),
    estimatedEndDate: rel(2),
    description: "Inspección para cotizar planta eléctrica de respaldo 20 KW.",
    address: "Av. Duarte 210, Villa Consuelo",
    total: 6_500,
    createdAt: rel(-1),
  },
];

export const inventory: InventoryItem[] = [
  { id: "i1", name: "Cable THHN #12 AWG (rollo 100m)", category: "Cables / conductores", sku: "CBL-12-100", costPrice: 3_200, salePrice: 4_500, stock: 42, minStock: 15, unit: "rollo" },
  { id: "i2", name: "Cable THHN #10 AWG (rollo 100m)", category: "Cables / conductores", sku: "CBL-10-100", costPrice: 4_900, salePrice: 6_800, stock: 8, minStock: 12, unit: "rollo" },
  { id: "i3", name: "Breaker 20A 1 polo Square D", category: "Breakers", sku: "BRK-20-1P", costPrice: 380, salePrice: 650, stock: 64, minStock: 20, unit: "unidad" },
  { id: "i4", name: "Breaker 2x30A Square D", category: "Breakers", sku: "BRK-30-2P", costPrice: 720, salePrice: 1_150, stock: 31, minStock: 15, unit: "unidad" },
  { id: "i5", name: "Panel 12 espacios con main 100A", category: "Paneles / tableros", sku: "PNL-12-100", costPrice: 4_100, salePrice: 6_200, stock: 6, minStock: 4, unit: "unidad" },
  { id: "i6", name: "Tomacorriente doble 15A grado hospital", category: "Tomacorrientes / interruptores", sku: "TOM-15-DBL", costPrice: 145, salePrice: 275, stock: 120, minStock: 40, unit: "unidad" },
  { id: "i7", name: "Interruptor sencillo blanco", category: "Tomacorrientes / interruptores", sku: "INT-1P-W", costPrice: 65, salePrice: 135, stock: 95, minStock: 30, unit: "unidad" },
  { id: "i8", name: "Panel solar 450W monocristalino", category: "Materiales solares", sku: "SOL-450", costPrice: 8_400, salePrice: 11_900, stock: 18, minStock: 8, unit: "unidad" },
  { id: "i9", name: "Inversor híbrido 5kW 48V", category: "Materiales solares", sku: "SOL-INV-5K", costPrice: 34_000, salePrice: 46_500, stock: 3, minStock: 2, unit: "unidad" },
  { id: "i10", name: "Cámara IP domo 4MP", category: "Materiales de cámaras y alarmas", sku: "CAM-4MP-D", costPrice: 2_100, salePrice: 3_400, stock: 24, minStock: 10, unit: "unidad" },
  { id: "i11", name: "Tubo EMT 1/2\" (tramo 3m)", category: "Tuberías / conduit", sku: "EMT-12-3M", costPrice: 210, salePrice: 360, stock: 140, minStock: 50, unit: "tramo" },
  { id: "i12", name: "Caja octagonal metálica", category: "Cajas eléctricas", sku: "CAJ-OCT", costPrice: 48, salePrice: 95, stock: 7, minStock: 25, unit: "unidad" },
];

export const quotes: Quote[] = [
  { id: "q1", number: "COT-2025-0091", clientId: "c3", clientName: "Ferretería El Tornillo Feliz", status: "enviada", subtotal: 285_000, discount: 10_000, itbis: 49_500, total: 324_500, createdAt: rel(-3), validUntil: rel(12) },
  { id: "q2", number: "COT-2025-0090", clientId: "c5", clientName: "Dra. Mariela Fernández", status: "aprobada", subtotal: 52_881, discount: 0, itbis: 9_519, total: 62_400, createdAt: rel(-6), validUntil: rel(9) },
  { id: "q3", number: "COT-2025-0089", clientId: "c1", clientName: "Residencial Los Cacicazgos", status: "aprobada", subtotal: 71_186, discount: 0, itbis: 12_814, total: 84_000, createdAt: rel(-4), validUntil: rel(11) },
  { id: "q4", number: "COT-2025-0088", clientId: "c6", clientName: "Colmadón El Buen Precio", status: "borrador", subtotal: 18_600, discount: 0, itbis: 3_348, total: 21_948, createdAt: rel(-1), validUntil: rel(14) },
  { id: "q5", number: "COT-2025-0087", clientId: "c7", clientName: "Hotel Boutique Villa Serena", status: "rechazada", subtotal: 210_000, discount: 0, itbis: 37_800, total: 247_800, createdAt: rel(-20), validUntil: rel(-5) },
];

export const invoices: Invoice[] = [
  { id: "f1", number: "FAC-2025-0203", ncf: "B0100000203", clientId: "c8", clientName: "Sr. Amparo Guzmán", status: "pendiente", subtotal: 349_831, itbis: 62_969, total: 412_800, createdAt: rel(-5) },
  { id: "f2", number: "FAC-2025-0202", ncf: "B0100000202", clientId: "c4", clientName: "Industrias Metálicas del Caribe", status: "pagada", subtotal: 122_881, itbis: 22_119, total: 145_000, paymentMethod: "Transferencia", createdAt: rel(-9) },
  { id: "f3", number: "FAC-2025-0201", ncf: "B0100000201", clientId: "c2", clientName: "Supermercado La Cadena — Suc. Naco", status: "pendiente", subtotal: 32_627, itbis: 5_873, total: 38_500, createdAt: rel(-2) },
  { id: "f4", number: "FAC-2025-0200", ncf: "B0100000200", clientId: "c7", clientName: "Hotel Boutique Villa Serena", status: "pagada", subtotal: 100_763, itbis: 18_137, total: 118_900, paymentMethod: "Efectivo", createdAt: rel(-12) },
];

export const activityFeed: ActivityEvent[] = [
  { id: "a1", type: "orden", title: "Nueva orden de emergencia", detail: "OS-2025-0152 · Colmadón El Buen Precio · sin energía en nevera", timestamp: rel(0) },
  { id: "a2", type: "pago", title: "Pago recibido", detail: "FAC-2025-0202 · RD$ 145,000.00 · Transferencia", timestamp: rel(0) },
  { id: "a3", type: "cotizacion", title: "Cotización aprobada", detail: "COT-2025-0090 · Dra. Mariela Fernández", timestamp: rel(-1) },
  { id: "a4", type: "inventario", title: "Stock bajo detectado", detail: "Inversor híbrido 5kW — quedan 3 unidades", timestamp: rel(-1) },
  { id: "a5", type: "orden", title: "Orden completada", detail: "OS-2025-0154 · Sistema solar 5kW · Sr. Amparo Guzmán", timestamp: rel(-2) },
  { id: "a6", type: "cliente", title: "Nuevo cliente registrado", detail: "Colmadón El Buen Precio · Los Mina", timestamp: rel(-3) },
];

// ── KPIs derivados ────────────────────────────────────────
export const dashboardKPIs = {
  activeOrders: serviceOrders.filter(
    (o) => !["completada", "facturada", "pagada", "cancelada"].includes(o.status)
  ).length,
  clients: clients.length,
  monthRevenue: invoices
    .filter((f) => f.status === "pagada")
    .reduce((s, f) => s + f.total, 0),
  pendingInvoices: invoices.filter((f) => f.status === "pendiente").length,
};

// Ingresos últimos 6 meses (para gráficas / finanzas).
export const revenueByMonth = [
  { month: "Feb", ingresos: 620_000, gastos: 410_000 },
  { month: "Mar", ingresos: 785_000, gastos: 452_000 },
  { month: "Abr", ingresos: 910_000, gastos: 498_000 },
  { month: "May", ingresos: 848_000, gastos: 471_000 },
  { month: "Jun", ingresos: 1_120_000, gastos: 560_000 },
  { month: "Jul", ingresos: 1_284_000, gastos: 602_000 },
];
